# Generated by Django 2.2 on 2019-06-19 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190617_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 15, 48, 21, 845710, tzinfo=utc)),
        ),
    ]
