# Generated by Django 2.2 on 2019-06-20 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190619_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 18, 19, 59, 52295, tzinfo=utc)),
        ),
    ]
